version: '3.9'
services:
    #Application
    guest_rolodex_app:
        container_name: guest_rolodex_app
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        command:
            npm run start:dev
        volumes:
            - ./:/usr/app 
        ports:
            - ${PORT}:${PORT}
        networks:
            - guest-rolodex-net
        depends_on:
            - guest_rolodex_db
        restart: on-failure
    #Database
    guest_rolodex_db:
        image: mysql:latest
        container_name: guest_rolodex_db
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - guest-rolodex-net
        volumes:
            - guest-rolodex-rdb:/var/lib/mysql
networks:
    guest-rolodex-net:
        driver: bridge
volumes:
    guest-rolodex-rdb:
